# Generated by Django 6.0.2 on 2026-02-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('respons', models.TextField()),
                ('education', models.TextField()),
                ('vacancies', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Remote Job', 'Remote Job')], max_length=20)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
